/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

/**
 *
 * @author AMD
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        flmMenuPrincipal = new javax.swing.JMenu();
        mntUsuarios = new javax.swing.JMenuItem();
        mntRegistro = new javax.swing.JMenuItem();
        mntVehiculos = new javax.swing.JMenuItem();
        mntIngresoVehiculos = new javax.swing.JMenuItem();
        mntFacturación = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        flmMenuPrincipal.setMnemonic('f');
        flmMenuPrincipal.setText("Menú");

        mntUsuarios.setMnemonic('o');
        mntUsuarios.setText("Usuarios");
        mntUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntUsuariosActionPerformed(evt);
            }
        });
        flmMenuPrincipal.add(mntUsuarios);

        mntRegistro.setMnemonic('s');
        mntRegistro.setText("Registro");
        mntRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntRegistroActionPerformed(evt);
            }
        });
        flmMenuPrincipal.add(mntRegistro);

        mntVehiculos.setMnemonic('a');
        mntVehiculos.setText("Vehículos");
        mntVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntVehiculosActionPerformed(evt);
            }
        });
        flmMenuPrincipal.add(mntVehiculos);

        mntIngresoVehiculos.setMnemonic('x');
        mntIngresoVehiculos.setText("Ingreso Vehículo");
        mntIngresoVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntIngresoVehiculosActionPerformed(evt);
            }
        });
        flmMenuPrincipal.add(mntIngresoVehiculos);

        mntFacturación.setText("Facturación");
        mntFacturación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntFacturaciónActionPerformed(evt);
            }
        });
        flmMenuPrincipal.add(mntFacturación);

        menuBar.add(flmMenuPrincipal);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntIngresoVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntIngresoVehiculosActionPerformed
        IngresoVehiculo ingresoVehiculo=new IngresoVehiculo();
        dskPanel.add(ingresoVehiculo);
        ingresoVehiculo.setVisible(true);
        
        
    }//GEN-LAST:event_mntIngresoVehiculosActionPerformed

    private void mntFacturaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntFacturaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntFacturaciónActionPerformed

    private void mntUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntUsuariosActionPerformed
        
        Usuarios usuarios=new Usuarios();
        dskPanel.add(usuarios);
        usuarios.setVisible(true);
        
        
    }//GEN-LAST:event_mntUsuariosActionPerformed

    private void mntRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntRegistroActionPerformed
        
       
    }//GEN-LAST:event_mntRegistroActionPerformed

    private void mntVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntVehiculosActionPerformed
        frmVehiculos vehiculos=new frmVehiculos();
        dskPanel.add(vehiculos);
        vehiculos.setVisible(true);
        
        
    }//GEN-LAST:event_mntVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPanel;
    private javax.swing.JMenu flmMenuPrincipal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mntFacturación;
    private javax.swing.JMenuItem mntIngresoVehiculos;
    private javax.swing.JMenuItem mntRegistro;
    private javax.swing.JMenuItem mntUsuarios;
    private javax.swing.JMenuItem mntVehiculos;
    // End of variables declaration//GEN-END:variables

}
